INSERT INTO events (project_id, trace_id, span_id, parent_span_id, start_time, end_time, name, type, environment, version, release, tags, trace_name, user_id, session_id, public, bookmarked, level, status_message, completion_start_time, prompt_id, prompt_name, prompt_version, model_id, provided_model_name, model_parameters, provided_usage_details, usage_details, provided_cost_details, cost_details, tool_definitions, tool_calls, tool_call_names, input, output, metadata, metadata_names, metadata_raw_values, source, service_name, service_version, scope_name, scope_version, telemetry_sdk_language, telemetry_sdk_name, telemetry_sdk_version, blob_storage_file_path, event_bytes, created_at, updated_at, event_ts, is_deleted)
SELECT o.project_id,
       o.trace_id,
       o.id AS span_id,
       o.parent_observation_id AS parent_span_id,
       o.start_time,
       o.end_time,
       o.name,
       o.type,
       o.environment,
       o.version,
       ifNull(t.release, '') as release,
       ifNull(t.tags, []) as tags,
       ifNull(t.name, '') as trace_name,
       ifNull(t.user_id, '') AS user_id,
       ifNull(t.session_id, '') AS session_id,
       ifNull(t.public, false) AS public,
       ifNull(t.bookmarked, false) AND (o.parent_observation_id IS NULL OR o.parent_observation_id == '') AS bookmarked,
       o.level,
       ifNull(o.status_message, '') AS status_message,
       o.completion_start_time,
       o.prompt_id,
       o.prompt_name,
       o.prompt_version,
       o.internal_model_id AS model_id,
       o.provided_model_name,
       coalesce(o.model_parameters, '{}'),
       o.provided_usage_details,
       o.usage_details,
       o.provided_cost_details,
       o.cost_details,
       o.tool_definitions,
       o.tool_calls,
       o.tool_call_names,
       ifNull(o.input, '') AS input,
       ifNull(o.output, '') AS output,
       CAST(o.metadata, 'JSON'),
       mapKeys(o.metadata) AS metadata_names,
       mapValues(o.metadata) AS metadata_raw_values,
       multiIf(mapContains(o.metadata, 'resourceAttributes'), 'otel', 'ingestion-api') AS source,
       NULL AS service_name, NULL AS service_version, NULL AS scope_name, NULL AS scope_version, NULL AS telemetry_sdk_language, NULL AS telemetry_sdk_name, NULL AS telemetry_sdk_version, '' AS blob_storage_file_path, 0 AS event_bytes, o.created_at, o.updated_at, o.event_ts, o.is_deleted
FROM observations o FINAL LEFT JOIN traces t ON o.trace_id = t.id WHERE (o.is_deleted = 0);

INSERT INTO events (project_id, trace_id, span_id, parent_span_id, start_time, name, type, environment, version, release, tags, trace_name, user_id, session_id, public, bookmarked, level, model_parameters, provided_usage_details, usage_details, provided_cost_details, cost_details, tool_definitions, tool_calls, tool_call_names, input, output, metadata, metadata_names, metadata_raw_values, source, service_name, service_version, scope_name, scope_version, telemetry_sdk_language, telemetry_sdk_name, telemetry_sdk_version, blob_storage_file_path, event_bytes, created_at, updated_at, event_ts, is_deleted)
SELECT t.project_id,
       t.id,
       t.id AS span_id,
       '' AS parent_span_id,
       t.timestamp,
       t.name,
       'SPAN',
       t.environment,
       t.version,
       t.release as release,
       t.tags as tags,
       t.name as trace_name,
       t.user_id AS user_id,
       t.session_id AS session_id,
       t.public AS public,
       t.bookmarked AS bookmarked,
       'DEFAULT' AS level,
       map() AS model_parameters, map(), map(), map(), map(), map(), [], [],
       ifNull(t.input, '') AS input,
       ifNull(t.output, '') AS output,
       CAST(t.metadata, 'JSON'),
       mapKeys(t.metadata) AS metadata_names,
       mapValues(t.metadata) AS metadata_raw_values,
       multiIf(mapContains(t.metadata, 'resourceAttributes'), 'otel', 'ingestion-api') AS source,
       NULL AS service_name, NULL AS service_version, NULL AS scope_name, NULL AS scope_version, NULL AS telemetry_sdk_language, NULL AS telemetry_sdk_name, NULL AS telemetry_sdk_version, '' AS blob_storage_file_path, 0 AS event_bytes, t.created_at, t.updated_at, t.event_ts, t.is_deleted
FROM traces t FINAL WHERE (t.is_deleted = 0);
