#!/usr/bin/env python3
"""Bring the LLM Gateway Stack up from a clean checkout, or refuse with a reason.

Same contract as the backplane's infra/bootstrap/prepare.ts: lock the env file, fill in
missing secrets, refuse to invent secrets over existing data, create the shared platform
network, start the stack, wait for readiness, print the next step. Exit codes: 0 ready,
1 refused (the JSON line on stderr names why), 2 bad usage, 3 the stack did not become
ready. Python 3.11+ standard library only.
"""

from __future__ import annotations

import argparse
import fcntl
import http.client
import json
import os
import re
import secrets
import shutil
import socket
import ssl
import subprocess
import sys
import time
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

PROJECT = "llm-gateway-stack"
NETWORK = "platform"
VOLUMES = ("clickhouse-data", "clickhouse-logs", "rustfs-data", "valkey-data", "caddy-data", "caddy-config")

# Secrets the stack needs and how many random bytes each gets (hex encoded).
SECRETS: dict[str, int] = {
    "LITELLM_MASTER_KEY": 32,
    "UI_PASSWORD": 24,
    "LITELLM_SALT_KEY": 24,
    "POSTGRES_PASSWORD": 24,
    "LG_POSTGRES_EXPORTER_PASSWORD": 24,
    "LITELLM_DB_PASSWORD": 24,
    "LANGFUSE_DB_PASSWORD": 24,
    "NEXTAUTH_SECRET": 32,
    "LANGFUSE_SALT": 24,
    "LANGFUSE_ENCRYPTION_KEY": 32,
    "CLICKHOUSE_PASSWORD": 24,
    "RUSTFS_ACCESS_KEY": 10,
    "RUSTFS_SECRET_KEY": 24,
    "VALKEY_PASSWORD": 24,
    "LANGFUSE_INIT_USER_PASSWORD": 16,
}
# Langfuse project keys keep the upstream prefixes so clients recognise them.
PREFIXED: dict[str, tuple[str, int]] = {
    "LANGFUSE_INIT_PROJECT_PUBLIC_KEY": ("pk-lf-", 16),
    "LANGFUSE_INIT_PROJECT_SECRET_KEY": ("sk-lf-", 24),
}
# Settings with a default the template already carries; bootstrap never rewrites them.
MANAGED = set(SECRETS) | set(PREFIXED) | {"UI_USERNAME"}
# Compose project names of earlier generations whose data must not be silently reused.
LEGACY_PROJECTS = ("llm-gateway", "litellm-langfuse")
IMAGE_LINE = re.compile(r"^\s+image:\s+(?P<ref>\S+)\s*$")
ENV_LINE = re.compile(r"^(?:export\s+)?(?P<key>[A-Z][A-Z0-9_]*)=(?P<value>.*)$")


class Refused(Exception):
    def __init__(self, code: str, detail: str = "") -> None:
        super().__init__(code)
        self.code = code
        self.detail = detail


Runner = Callable[[list[str]], subprocess.CompletedProcess[str]]


def run(argv: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(argv, text=True, capture_output=True, check=False)


def read_env(path: Path) -> tuple[list[str], dict[str, str]]:
    """Return the raw lines and the managed assignments. Unmanaged lines are kept verbatim."""
    if not path.exists():
        return [], {}
    lines = path.read_text(encoding="utf-8").splitlines()
    values: dict[str, str] = {}
    for line in lines:
        match = ENV_LINE.match(line)
        if not match:
            continue
        key, value = match.group("key"), match.group("value")
        if key in MANAGED:
            if key in values:
                raise Refused("env_repair_required", f"{key} is set twice in {path}")
            if value.startswith(("'", '"')) or "${" in value:
                raise Refused("env_repair_required", f"{key} must be a plain value in {path}")
            values[key] = value
    return lines, values


def generate(missing: set[str]) -> dict[str, str]:
    fresh: dict[str, str] = {}
    for key in sorted(missing):
        if key == "UI_USERNAME":
            fresh[key] = "admin"
        elif key in SECRETS:
            fresh[key] = secrets.token_hex(SECRETS[key])
        else:
            prefix, size = PREFIXED[key]
            fresh[key] = prefix + secrets.token_hex(size)
    return fresh


def write_env(path: Path, lines: list[str], template: Path, fresh: dict[str, str]) -> None:
    if not lines:
        lines = template.read_text(encoding="utf-8").splitlines()
        lines += ["", "# Generated by scripts/bootstrap.py. Keep this file private and backed up."]
    lines += [f"{key}={value}" for key, value in fresh.items()]
    tmp = path.with_name(path.name + ".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    os.replace(tmp, path)
    os.chmod(path, 0o600)


def unquote(value: str) -> str:
    """Compose accepts 'x' and "x"; a bare value is used as is."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def backup_policy(settings: dict[str, str]) -> bool:
    """Storage policy follows Compose precedence, including an explicitly empty shell value."""
    value = os.environ.get("LG_ALLOW_SAME_FILESYSTEM_BACKUP",
                           settings.get("LG_ALLOW_SAME_FILESYSTEM_BACKUP", "false"))
    if value not in ("true", "false"):
        raise Refused("invalid_backup_policy", "LG_ALLOW_SAME_FILESYSTEM_BACKUP must be true or false")
    if value == "true":
        print("WARNING: development same-filesystem backups enabled; disk loss affects both "
              "live data and backups. This does not meet the production backup contract.", file=sys.stderr)
    return value == "true"


def check_backup_storage(backups: Path, data: Path, allow_same_filesystem: bool = False) -> None:
    backups, data = backups.resolve(), data.resolve()
    if not backups.is_dir():
        raise Refused("backup_dir_missing", "LG_BACKUP_DIR must exist and its storage must be mounted")
    if backups.is_relative_to(data) or data.is_relative_to(backups):
        raise Refused("backup_dir_overlap", "backup and Postgres data paths must not overlap")
    # Inspect the nearest existing parent before creating the cluster directory.
    parent = data
    while not parent.exists():
        parent = parent.parent
    if backups.stat().st_dev == parent.stat().st_dev and not allow_same_filesystem:
        raise Refused("backup_dir_same_filesystem", "backup and Postgres data must use different filesystems")


def project_name(settings: dict[str, str]) -> str:
    """Same precedence as Compose: shell environment, then the env file, then name:."""
    return os.environ.get("COMPOSE_PROJECT_NAME") or unquote(settings.get("COMPOSE_PROJECT_NAME", "")) or PROJECT


def installation_state(root: Path, data_dir: Path, runner: Runner, project: str = PROJECT,
                       prefix: str = PROJECT) -> list[str]:
    """Every place an earlier installation of this project could have left data."""
    found: list[str] = []
    prefixes = tuple(f"{name}_" for name in (project, *LEGACY_PROJECTS))
    if data_dir.exists():
        if not os.access(data_dir, os.R_OK | os.X_OK):
            raise Refused("postgres_dir_unreadable", str(data_dir))
        if any(data_dir.iterdir()):
            found.append(f"postgres data at {data_dir}")
    result = runner(["docker", "volume", "ls", "--format", "{{.Name}}"])
    if result.returncode != 0:
        raise Refused("docker_unavailable", result.stderr.strip())
    for name in result.stdout.split():
        if name.startswith(prefixes) or name in volume_names(prefix):
            found.append(f"volume {name}")
    return found


def images(compose: Path) -> dict[str, str]:
    """Service name to image tag, read from compose.yaml without a YAML parser."""
    out: dict[str, str] = {}
    service = ""
    for line in compose.read_text(encoding="utf-8").splitlines():
        head = re.match(r"^  (?P<name>[a-z][a-z0-9-]*):\s*$", line)
        if head:
            service = head.group("name")
        match = IMAGE_LINE.match(line)
        if match and service:
            ref = match.group("ref").split("@", 1)[0]
            out[service] = ref.rsplit(":", 1)[-1]
    return out


def write_versions(root: Path, compose: Path) -> None:
    console = root / "data" / "console"
    console.mkdir(parents=True, exist_ok=True)
    tags = images(compose)
    doc = {
        "pinnedAt": datetime.fromtimestamp(compose.stat().st_mtime, timezone.utc).isoformat(),
        "images": {
            "litellm": tags.get("litellm", "unknown").lstrip("v"),
            "langfuse": tags.get("langfuse-web", "unknown"),
            "rustfs": tags.get("rustfs", "unknown"),
            "postgres": tags.get("postgres", "unknown"),
            "clickhouse": tags.get("clickhouse", "unknown"),
            "valkey": tags.get("valkey", "unknown"),
            "caddy": tags.get("caddy", "unknown"),
        },
    }
    (console / "versions.json").write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")


def volume_names(prefix: str) -> list[str]:
    return [f"{prefix}-{name}" for name in VOLUMES]


def ensure_volumes(runner: Runner, prefix: str = PROJECT) -> None:
    result = runner(["docker", "volume", "ls", "--format", "{{.Name}}"])
    if result.returncode:
        raise Refused("docker_unavailable", result.stderr.strip())
    existing = set(result.stdout.split())
    for name in volume_names(prefix):
        if name not in existing:
            result = runner(["docker", "volume", "create", name])
            if result.returncode:
                raise Refused("volume_create_failed", result.stderr.strip())


def ensure_network(runner: Runner, name: str = NETWORK) -> None:
    probe = runner(["docker", "network", "inspect", name])
    if probe.returncode == 0:
        return
    created = runner(["docker", "network", "create", name])
    if created.returncode != 0:
        raise Refused("network_create_failed", created.stderr.strip())


def compose_up(root: Path, env_file: Path, runner: Runner) -> None:
    result = runner([
        "docker", "compose", "--project-directory", str(root), "--env-file", str(env_file),
        "up", "--detach", "--wait", "--wait-timeout", "300",
    ])
    if result.returncode != 0:
        raise Refused("compose_up_failed", (result.stderr or result.stdout).strip()[-2000:])


def access_settings(settings: dict[str, str]) -> dict[str, str]:
    values = dict(settings)
    mode = values.get("LG_ACCESS_MODE") or "local"
    defaults = {
        "local": ("http", "dual", "internal"),
        "public": ("https", "https", "acme"),
        "proxy": ("https", "http", "none"),
    }
    if mode not in defaults:
        raise Refused("invalid_access_mode", "LG_ACCESS_MODE must be local, public or proxy")
    values["LG_ACCESS_MODE"] = mode
    values["LG_SCHEME"] = values.get("LG_SCHEME") or defaults[mode][0]
    values["LG_LISTEN_SCHEME"], values["LG_TLS_ISSUER"] = defaults[mode][1:]
    values.setdefault("LG_PUBLIC_DOMAIN", "localhost")
    if not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9.-]*", values["LG_PUBLIC_DOMAIN"]):
        raise Refused("invalid_access_settings", "LG_PUBLIC_DOMAIN must be a DNS hostname")
    if re.fullmatch(r"[0-9.]+", values["LG_PUBLIC_DOMAIN"]):
        raise Refused("invalid_access_settings", "use a DNS application domain; 127.0.0.1 is a Local Mode root alias")
    if not re.fullmatch(r"(?::[0-9]+)?", values.get("LG_PUBLIC_PORT_SUFFIX", "")):
        raise Refused("invalid_access_settings", "LG_PUBLIC_PORT_SUFFIX must be empty or :port")
    bind = values.get("LG_BIND_HOST") or "127.0.0.1"
    # Include bracketed and expanded IPv6 wildcard spellings accepted by Compose.
    if mode == "proxy" and (bind == "0.0.0.0" or re.fullmatch(r"\[?[0:]*:[0:]*\]?", bind)):
        raise Refused("invalid_access_settings", "proxy requires a loopback or specific-interface LG_BIND_HOST; "
                      "see docs/operations/ingress.md")
    if (values["LG_SCHEME"] not in ("http", "https")
            or (mode == "public" and values["LG_SCHEME"] != "https")
            or (mode == "proxy" and not values.get("LG_TRUSTED_PROXIES", "").strip())
            or (mode == "public" and (values["LG_PUBLIC_DOMAIN"] == "localhost"
                                      or values["LG_PUBLIC_DOMAIN"].endswith(".localhost")))):
        raise Refused("invalid_access_settings", "invalid public origin or missing proxy trust; "
                      "see docs/operations/ingress.md")
    files = values.get("COMPOSE_FILE", "compose.yaml:compose.${LG_ACCESS_MODE:-local}.yaml")
    files = files.replace("${LG_ACCESS_MODE:-local}", mode).split(os.pathsep)
    if mode != "local" and not any(Path(name).name == f"compose.{mode}.yaml" for name in files):
        raise Refused("invalid_access_settings", f"COMPOSE_FILE must include compose.{mode}.yaml")
    return values


class LocalHTTPSConnection(http.client.HTTPSConnection):
    """Connect to the local listener while verifying the public TLS hostname."""

    def __init__(self, hostname, port, address, context):
        super().__init__(hostname, port, timeout=5, context=context)
        self.address = address
        self.context = context

    def connect(self):
        sock = socket.create_connection((self.address, self.port), self.timeout)
        try:
            self.sock = self.context.wrap_socket(sock, server_hostname=self.host)
        except BaseException:
            sock.close()
            raise


def wait_ready(url: str, timeout: float = 120.0, host: str | None = None,
               context: ssl.SSLContext | None = None) -> None:
    parsed = urllib.parse.urlsplit(url)
    deadline = time.monotonic() + timeout
    last = ""
    while time.monotonic() < deadline:
        connection = (LocalHTTPSConnection(host or parsed.hostname, parsed.port,
                                           parsed.hostname, context or ssl.create_default_context())
                      if parsed.scheme == "https" else
                      http.client.HTTPConnection(parsed.hostname, parsed.port, timeout=5))
        try:
            connection.request("GET", parsed.path, headers={"Host": host} if host else {})
            response = connection.getresponse()
            if response.status == 200:
                return
            last = f"http {response.status}"
        except (OSError, http.client.HTTPException) as error:
            last = str(error)
        finally:
            connection.close()
        time.sleep(3)
    raise Refused("not_ready", f"{url}: {last}")


def probe_gateway(settings, command, runner):
    settings = access_settings(settings)
    domain = settings.get("LG_PUBLIC_DOMAIN", "localhost")
    bind = settings.get("LG_BIND_HOST", "127.0.0.1")
    address = "127.0.0.1" if bind in ("0.0.0.0", "127.0.0.1", "") else bind
    if address == "::":
        address = "::1"
    schemes = ("http", "https") if settings["LG_ACCESS_MODE"] == "local" else (settings["LG_LISTEN_SCHEME"],)
    for scheme in schemes:
        port = settings.get("LG_HTTPS_PORT" if scheme == "https" else "LG_HTTP_PORT") or ("443" if scheme == "https" else "80")
        context = None
        if scheme == "https":
            context = ssl.create_default_context()
            if settings["LG_TLS_ISSUER"] == "internal":
                result = runner(command + ["exec", "-T", "caddy", "cat",
                                           "/data/caddy/pki/authorities/local/root.crt"])
                if result.returncode:
                    raise Refused("internal_ca_unavailable", "cannot read Caddy's internal root certificate")
                context.load_verify_locations(cadata=result.stdout)
        local = f"{scheme}://{'[' + address + ']' if ':' in address else address}:{port}"
        for path in ("/health/litellm", "/health/langfuse"):
            wait_ready(local + path, host=domain, context=context)


def bootstrap(argv: list[str], runner: Runner = run) -> int:
    parser = argparse.ArgumentParser(prog="bootstrap.py", description=__doc__.splitlines()[0])
    parser.add_argument("--env-file", default=".env")
    parser.add_argument("--template", default=".env.example")
    parser.add_argument("--render-only", action="store_true",
                        help="write the env file, start nothing")
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parent.parent
    env_file = (root / args.env_file).resolve()
    template = (root / args.template).resolve()
    compose = root / "compose.yaml"

    if shutil.which("docker") is None and not args.render_only:
        raise Refused("docker_missing", "install Docker with the Compose plugin")

    lock_path = env_file.with_name(env_file.name + ".lock")
    with open(lock_path, "w", encoding="utf-8") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            raise Refused("bootstrap_already_running", str(lock_path)) from error

        lines, present = read_env(env_file)
        # Compose lets the shell override the env file. A shell value that differs from
        # the saved one would run the stack with a secret the file does not record.
        conflicts = sorted(k for k in MANAGED if k in present and k in os.environ and os.environ[k] != present[k])
        if conflicts:
            raise Refused("shell_env_conflict", "unset in the shell or fix .env: " + ", ".join(conflicts))
        missing = MANAGED - set(present)
        settings = {
            m.group("key"): unquote(m.group("value"))
            for m in (ENV_LINE.match(line) for line in (lines or template.read_text().splitlines())) if m
        }
        # Match Compose's shell precedence for operator settings as well as secrets.
        settings.update({key: value for key, value in os.environ.items()
                         if key in settings or key.startswith("LG_") or key == "COMPOSE_FILE"})
        settings = access_settings(settings)
        allow_same_filesystem = backup_policy(settings)
        project = project_name(settings)
        prefix = os.environ.get("LG_VOLUME_PREFIX", settings.get("LG_VOLUME_PREFIX")) or PROJECT
        data_dir_setting = os.environ.get("LG_POSTGRES_DATA_DIR") or settings.get("LG_POSTGRES_DATA_DIR", "./data/postgres")
        data_dir = Path(data_dir_setting) if os.path.isabs(data_dir_setting) else (root / data_dir_setting).resolve()
        installation = env_file == (root / ".env").resolve()

        # --render-only on a scratch env file (validate.sh, tests) touches nothing but that
        # file. On the installation's own .env the guard still applies: no new secrets
        # over existing data, in any mode.
        if missing and (installation or not args.render_only):
            existing = installation_state(root, data_dir, runner, project, prefix)
            if existing:
                raise Refused(
                    "existing_installation_missing_secrets",
                    "restore the original .env before starting; found " + "; ".join(existing),
                )
        if missing:
            fresh = generate(missing)
            # A secret supplied in the shell on a fresh install is the operator's choice;
            # record it instead of generating a different one.
            fresh.update({k: os.environ[k] for k in missing if os.environ.get(k)})
            write_env(env_file, lines, template, fresh)
        if args.render_only:
            print(json.dumps({"env": str(env_file), "project": project, "generated": sorted(missing)}))
            return 0

        email = settings.get("LANGFUSE_INIT_USER_EMAIL", "").strip()
        if not email or email.lower().endswith("@example.com"):
            raise Refused("langfuse_login_required", "set LANGFUSE_INIT_USER_EMAIL to your login email")
        backup_setting = os.environ.get("LG_BACKUP_DIR", settings.get("LG_BACKUP_DIR", ""))
        if not backup_setting:
            raise Refused("backup_dir_required", "set LG_BACKUP_DIR to a separate mounted filesystem")
        backup_dir = (root / backup_setting).resolve()
        check_backup_storage(backup_dir, data_dir, allow_same_filesystem)

        # 0755: the postgres user must traverse this directory to reach its cluster,
        # which the image creates underneath as 18/docker with mode 0700.
        data_dir.mkdir(parents=True, exist_ok=True, mode=0o755)
        os.chmod(data_dir, 0o755)
        write_versions(root, compose)

        ensure_network(runner, settings.get("LG_PLATFORM_NETWORK", NETWORK))
        ensure_volumes(runner, prefix)
        compose_up(root, env_file, runner)
        scheme = settings.get("LG_SCHEME", "http")
        domain = settings.get("LG_PUBLIC_DOMAIN", "localhost")
        origin = domain + settings.get("LG_PUBLIC_PORT_SUFFIX", "")
        probe_gateway(settings, ["docker", "compose", "--project-directory", str(root),
                                 "--env-file", str(env_file)], runner)
        print(json.dumps({
            "console": f"{scheme}://{origin}/",
            "litellm": f"{scheme}://litellm.{origin}/",
            "langfuse": f"{scheme}://langfuse.{origin}/",
            "langfuseLogin": email,
            "next": "Log in to Langfuse with the email above and LANGFUSE_INIT_USER_PASSWORD from .env; "
                    "call the API with LITELLM_MASTER_KEY or create a virtual key in LiteLLM.",
        }))
        return 0


def main() -> int:
    try:
        return bootstrap(sys.argv[1:])
    except Refused as refused:
        print(json.dumps({"error": refused.code, "detail": refused.detail}), file=sys.stderr)
        return 3 if refused.code in ("not_ready", "compose_up_failed") else 1
    except SystemExit as exit_:  # argparse
        return 2 if exit_.code not in (0, None) else 0


if __name__ == "__main__":
    raise SystemExit(main())
